version: '3'
services:

  books:
    build: 
      context: ./services/book/app
      dockerfile: Dockerfile
    container_name: books
    working_dir: /var/www/test/app
    volumes: 
      - ./services/book/app:/var/www/test/app
    hostname: books
    ports:
      - "3002:3001"
    depends_on: 
      - grpcserver
    command: bash -c "npm rebuild && npm start"
    
  grpcserver:
    build:
      context: ./services/book/api
      dockerfile: Dockerfile 
    container_name: grpcserver
    working_dir: /var/www/test/api
    hostname: grpcserver
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
    command: bash -c "npm rebuild && npm start"

  db:
    image: mongo
    ports:
      - "27017:27017"
  
  videos:
    build: 
      context: ./services/videos/app
      dockerfile: Dockerfile
    container_name: videos
    working_dir: /var/www/videos/app
    volumes: 
      - ./services/videos/app:/var/www/videos/app
    hostname: videos
    ports:
      - "3003:3001"
    depends_on: 
      - grpcserver
    command: bash -c "npm rebuild && npm start"

  nginx:
    image: nginx:latest
    container_name: gateway-nginx
    ports:
      - 443:443
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - books
      - grpcserver
      - videos
