version: '3'
services:

  books:
    build: 
      context: ./books
      dockerfile: Dockerfile
    container_name: books
    working_dir: /var/www/test/books
    volumes: 
      - ./books:/var/www/test/books
    hostname: books
    depends_on: 
      - grpcserver
    command: bash -c "npm rebuild && npm start"
    
  grpcserver:
    build:
      context: ./grpcserver
      dockerfile: Dockerfile 
    container_name: grpcserver
    working_dir: /var/www/test/grpcserver
    hostname: grpcserver
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
    command: bash -c "npm rebuild && npm start"

  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    container_name: gateway-nginx
    ports:
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - books
      - grpcserver
